# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Stream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Stream.proto',
  package='StreamServer',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cStream.proto\x12\x0cStreamServer\"\x1e\n\x0bTestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\r\n\x0bTestRequest\"$\n\x11TestStreamMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11TestStreamRequest2\xab\x01\n\rStreamService\x12\x42\n\x08testFunc\x12\x19.StreamServer.TestRequest\x1a\x19.StreamServer.TestMessage\"\x00\x12V\n\x0etestStreamFunc\x12\x1f.StreamServer.TestStreamRequest\x1a\x1f.StreamServer.TestStreamMessage\"\x00\x30\x01\x62\x06proto3'
)




_TESTMESSAGE = _descriptor.Descriptor(
  name='TestMessage',
  full_name='StreamServer.TestMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StreamServer.TestMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=60,
)


_TESTREQUEST = _descriptor.Descriptor(
  name='TestRequest',
  full_name='StreamServer.TestRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=75,
)


_TESTSTREAMMESSAGE = _descriptor.Descriptor(
  name='TestStreamMessage',
  full_name='StreamServer.TestStreamMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='StreamServer.TestStreamMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=113,
)


_TESTSTREAMREQUEST = _descriptor.Descriptor(
  name='TestStreamRequest',
  full_name='StreamServer.TestStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=134,
)

DESCRIPTOR.message_types_by_name['TestMessage'] = _TESTMESSAGE
DESCRIPTOR.message_types_by_name['TestRequest'] = _TESTREQUEST
DESCRIPTOR.message_types_by_name['TestStreamMessage'] = _TESTSTREAMMESSAGE
DESCRIPTOR.message_types_by_name['TestStreamRequest'] = _TESTSTREAMREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TestMessage = _reflection.GeneratedProtocolMessageType('TestMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTMESSAGE,
  '__module__' : 'Stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamServer.TestMessage)
  })
_sym_db.RegisterMessage(TestMessage)

TestRequest = _reflection.GeneratedProtocolMessageType('TestRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTREQUEST,
  '__module__' : 'Stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamServer.TestRequest)
  })
_sym_db.RegisterMessage(TestRequest)

TestStreamMessage = _reflection.GeneratedProtocolMessageType('TestStreamMessage', (_message.Message,), {
  'DESCRIPTOR' : _TESTSTREAMMESSAGE,
  '__module__' : 'Stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamServer.TestStreamMessage)
  })
_sym_db.RegisterMessage(TestStreamMessage)

TestStreamRequest = _reflection.GeneratedProtocolMessageType('TestStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _TESTSTREAMREQUEST,
  '__module__' : 'Stream_pb2'
  # @@protoc_insertion_point(class_scope:StreamServer.TestStreamRequest)
  })
_sym_db.RegisterMessage(TestStreamRequest)



_STREAMSERVICE = _descriptor.ServiceDescriptor(
  name='StreamService',
  full_name='StreamServer.StreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=308,
  methods=[
  _descriptor.MethodDescriptor(
    name='testFunc',
    full_name='StreamServer.StreamService.testFunc',
    index=0,
    containing_service=None,
    input_type=_TESTREQUEST,
    output_type=_TESTMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='testStreamFunc',
    full_name='StreamServer.StreamService.testStreamFunc',
    index=1,
    containing_service=None,
    input_type=_TESTSTREAMREQUEST,
    output_type=_TESTSTREAMMESSAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAMSERVICE)

DESCRIPTOR.services_by_name['StreamService'] = _STREAMSERVICE

# @@protoc_insertion_point(module_scope)
